### ISSUE TITLE
station_code and panel_code should be optional parameters

### ISSUE THREAD

**Issue by prakashautade** [coppeliaMLA/pybarb#14]
In BARB APIs `/api/v1/advertising_spots/`, `/api/v1/audiences_by_time/` and `/api/v1/programme_ratings/` query parameters `station_code` and `panel_code` are optional but in SDK they are compulsory parameters.
Getting the following error while retrieving advertising_spots

`Traceback (most recent call last):
  File "test.py", line 25, in <module>
    get_report()
  File "test.py", line 19, in get_report
    advertising_spots = barb_api.advertising_spots("2020-01-01", "2020-01-02")
  File "D:\work\choreograph\repositories\py-barb\.venv\lib\site-packages\pybarb\pybarb.py", line 148, in advertising_spots
    "station_code": self.get_station_code(station), "panel_code": self.get_panel_code(panel),
  File "D:\work\choreograph\repositories\py-barb\.venv\lib\site-packages\pybarb\pybarb.py", line 66, in get_station_code
    station_code = [s["station_code"]
  File "D:\work\choreograph\repositories\py-barb\.venv\lib\site-packages\pybarb\pybarb.py", line 67, in <listcomp>
    for s in api_data if station_name.lower() == s['station_name'].lower()]
AttributeError: 'NoneType' object has no attribute 'lower'`

We have to download the data for all stations and panels.
Can SDK make these parameters optional?

**Comment by coppeliaMLA** [comment]
Hi @prakashautade As with the comment on the other issue, you could either wait for me to implement or we would welcome collaborators. It would be good to know a bit about your business. We could discuss this directly if you would rather keep it confidential.

**Comment by coppeliaMLA** [comment]
Hi @prakashautade this is now fixed in the latest commit to main (plus a bug in `query_event_endpoint`) If you are installing from pip I will update that tomorrow. Please test though. Code is provide 'as is'!

**Comment by coppeliaMLA** [comment]
Hi @prakashautade Just checking if this worked for you. If so I'll close the ticket
